PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?sign mobiliteit:heeftMogelijkOnderbord ?subsign .
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/mow/registry> {
    ?sign a mobiliteit:Verkeersbordconcept ;
          mobiliteit:heeftMogelijkOnderbord ?subsign .
  }
}
