PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
  ?doc eli:date_publication ?oldDate .
}
INSERT {
  ?doc eli:date_publication ?newDate .
}
WHERE {
  VALUES ?zitting { }
  ?zitting a besluit:Zitting .
  ?zitting ext:besluitenlijst ?doc .
  ?doc a ext:Besluitenlijst .
  ?doc prov:wasDerivedFrom ?pr .
  ?pr dct:created ?newDate .
  ?doc eli:date_publication ?oldDate .
}
