PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?sign ?codeProd ?codeQa
WHERE {
  SERVICE <http://db.mow-qa.localhost/sparql> {
    GRAPH <http://mu.semte.ch/graphs/mow/registry> {
      ?sign a mobiliteit:Verkeersbordconcept ;
             skos:prefLabel ?codeQa .
    }
  }
  SERVICE <http://db.mow-prod.localhost/sparql> {
    GRAPH <http://mu.semte.ch/graphs/mow/registry> {
      ?sign a mobiliteit:Verkeersbordconcept ;
             skos:prefLabel ?codeProd .
    }
  }
  FILTER (?codeQa != ?codeProd)
}
