PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

SELECT DISTINCT ?dir ?p (GROUP_CONCAT(DISTINCT ?type; SEPARATOR = ";") AS ?types)
WHERE {
  ?z a besluit:Zitting .
  {
    ?z ?p ?o .
    VALUES ?dir { "out" }
  }
  UNION
  {
    ?o ?p ?z .
    VALUES ?dir { "in" }
  }
  OPTIONAL {
    ?o a ?type .
  }
}
GROUP BY ?p ?dir
ORDER BY ASC(?dir)
