PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
SELECT DISTINCT ?p (GROUP_CONCAT(?type; SEPARATOR = ";") as ?types) WHERE {
  ?z a besluit:Zitting.
  ?z ?p ?o.
  OPTIONAL {
    ?o a ?type.
  }

} GROUP BY ?p
